corpus:
  name: WeeBit
  reprocess: False

k_fold: 5

subsample_splits: 10

short_name: Flesch Score + SVM

runner_type: cpu_multi

features:
  - name: Flesch
    reprocess: False

model: 
  name: svm
