corpus:
  name: WeeBit
  reprocess: False
  limit: 600


k_fold: 5

subsample_splits: 1

short_name: Logistic regression classification with word types and word count Limit 600

runner_type: cpu_multi

features:
  - name: WordTypeProportions
    reprocess: False
  - name: WordCount
    reprocess: False

model: 
  name: LogisticRegression

run: False