corpus:
  name: WeeBit
  reprocess: False

k_fold: 5

subsample_splits: 1

short_name: Cnn ordered class regression fed word vectors

runner_type: gpu

model: 
  name: cnn_regression
  params:
    epochs: 30
    nn_model: cnn_regression
  regression: ordered_classes
  overwrite: True

run: False