corpus:
  name: WeeBit
  reprocess: False
  limit: 600

k_fold: 5

subsample_splits: 1

short_name: Cnn age regression fed word vectors Limit 600

runner_type: gpu

model: 
  name: cnn_regression
  params:
    epochs: 30
    nn_model: cnn_regression
  regression: age
  overwrite: True

run: False