corpus:
  name: WeeBit
  reprocess: False
  limit: 600


k_fold: 5

subsample_splits: 1

short_name: Logistic regression classification with word types, Flesch features, and ling features Limit 600

runner_type: cpu_multi

features:
  - name: WordTypeProportions
    reprocess: False
  - name: WordCount
    reprocess: False
  - name: SentenceCount
    reprocess: False
  - name: SyllableCount
    reprocess: False
  - name: JavaImporter
    reprocess: True

model: 
  name: svm

run: False