corpus:
  name: WeeBit
  reprocess: False
  limit: 600

k_fold: 5

subsample_splits: 1

short_name: Transfomer classification fed word vectors + SVM Limit 600

runner_type: gpu

features:
  - name: Neural
    model_config: configs/WeeBit/transformer600.yaml
    reprocess: True


model: 
  name: svm

run: False

