corpus:
  name: WeeBit
  reprocess: False

k_fold: 5

subsample_splits: 10

short_name: Cnn classification fed word vectors + SVM

runner_type: gpu

features:
  - name: Neural
    model_config: configs/WeeBit/cnn.yaml
    reprocess: True


model: 
  name: svm
