corpus:
  name: WeeBit
  reprocess: False
  limit: 600

k_fold: 5

subsample_splits: 1

short_name: Classification CNN (fed word vectors) 600 limit

runner_type: gpu

model: 
  name: cnn
  params:
    epochs: 30
    nn_model: cnn
  overwrite: False
