corpus:
  name: WeeBit
  reprocess: False

k_fold: 5

subsample_splits: 10

short_name: Word types + SVM

runner_type: cpu_multi

features:
  - name: WordTypes
    reprocess: False

model: 
  name: svm
