corpus:
  name: WeeBit
  reprocess: False

k_fold: 5

subsample_splits: 10

short_name: Flesch Features + SVM

runner_type: cpu_multi

features:
  - name: WordCount
  - name: SentenceCount
  - name: SyllableCount


model: 
  name: svm
