corpus:
  name: Newsela
  reprocess: True

k_fold: 5

subsample_splits: 1

short_name: Classification CNN (fed word vectors)

runner_type: gpu

model: 
  name: cnn
  params:
    epochs: 30
    nn_model: cnn
  overwrite: True

run: False
