corpus:
  name: Newsela
  reprocess: True
  

k_fold: 5

subsample_splits: 1

short_name: Flesch features + linear regression

runner_type: cpu_multi

features:
  - name: WordCount
    reprocess: True
  - name: SentenceCount
    reprocess: True
  - name: SyllableCount
    reprocess: True

model: 
  name: LinearSVC

run: False