corpus:
  name: Newsela
  reprocess: True

k_fold: 5

subsample_splits: 1

short_name: Logistic regression classification with word types (non normalized)

runner_type: cpu_multi

features:
  - name: WordTypes
    reprocess: False

model: 
  name: LogisticRegression

run: False