corpus:
  name: Newsela
  reprocess: True
  

k_fold: 5

subsample_splits: 1

short_name: ~100 Ling features + SVM

runner_type: cpu_multi

features:
  - name: JavaImporter
    reprocess: True

model: 
  name: svm

run: False