corpus:
  name: Newsela
  reprocess: True
  

k_fold: 5

subsample_splits: 1

short_name: Flesch Features + SVM

runner_type: cpu_multi

features:
  - name: WordCount
    reprocess: True
  - name: SentenceCount
    reprocess: True
  - name: SyllableCount
    reprocess: True


model: 
  name: svm

run: False